version: '3'

services:

  bridge:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LEDGER: ach
        SERVER_URL: ldg-dev.one

  client:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        LEDGER: ach
        SERVER_URL: ldg-dev.one